language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: uzgE9WJ0RGx2B/Y/F70jTVhcnjCLgmkL08ELcIgfFPn6p4uS5c8uua80ZHpLJaOcFtOnYS+CLGnQmLTgK7VL9XktA7li1lqhQsscshHD1RWf36zDEax3sehLxf4yQRd5kzyp1oq5hqD5q0UgWzgvB7I1uwsnHsNrpQwA/0EvqLxuZ7ZuOhD2bZy0Vv8Jk0FZTkhLii5jZD2tfcXO63bQUfS/iqy9dV0yt3kEku8b1DphM5OJpCA9DKNNQ83OSe9Ci+iAvuaXBvVj5wJsssj4X+kfZQ5c5n3XOQOlxOl8o5bO1hk3DMWFgdXG3QhXCrW7FdQW3apiXHHSG1eLAAocCqPd3nX1wXrhqaDGDx0qYd+RQ+Dfs2/VV7z5wgqWYkCiQm2Rcctoclr62ORavH3908U0a/fJO5yXmwNQjs7GvFCSwZg20aKR2fl1ZOGcFrSlmOK5wU4kQXEFiJV3C/SKAxNXiuI/uHAwbQfUPsLi7SPh/pLhdgvAOp6cYy1U0P4JYf4V3YWuEXttGUXuua8a9xsTnLys6o05UzQS3UV1NVqkK8LDsH6mJrKWp66h2ZWb4r5/nWG5VJ6RIpw5IqSiEHbym2Tt5L/KKy4FFAfmsU2Lnmexu4Wg6Mena/0/NwRgV9afmgsNkVdljE4Kevb+9tOC90vI6r0U7xXnXdrxmd4=
  - secure: g+/fuFmi+jJJIpQ/qaQnfrJdAuALz9lHpYy4Kew/Cf8sFK0Za/GNAVHK0OkjcNFKPSwmoSJEn4liPjyrBqJ6Fe9YmA83JpTVJhLgB9aVWpHTaF54im8RyrEtHW0o/+s2D7dKsrjmcQ5nik9q34GJ1SNtAjY0L1D3KmaJZ/KU6eruICP2vH0fX8lPDBv98voZrdQMeFE3IRv3/O4lgKewZK6bMyzSC1FI7EeUadrW/D6HfOcRjU4oOe+oksp7vdObmjfUqO0SxWIH5PftKuGBu40yFrLQddKVzITLbf6tpGZEZq4paSLVjo2vZ4kt420rdBemQK++VJ7WIXOifQaelo65kq4TS8EqTEdmMs1NO9gRhO/5im+buzeRu/PV52Zm+8UXuQ3JHFGW14ZAMEJq71riiNu+zuejwLF9FiXcCVFUC//uenbaXUCiQBdnKBGfMlG2XhIFs9HCH9mFSV5P3h1TthVcQpxtgBXiG8KryW9vx0wMkTvrw1EFnWHLeu4JJG34xBLtnCb+iHtXANixlBlsVGOkjImSWCu2FzOUWVdoEX+Edzdqdf4+fI+UKuHRBMS7YXOqpfQWbA93UXL8wOQpHMf/fNx0s25tnbnCiNKyRrz4eaLXRmbUrE4yWkYp28ML7W+Ajvk1EK/vwpmTeW/LIqByRmjGMD8mhhhyapQ=
  - secure: t/n9GZBXBWBqfYZMJiZOg05uv6AqKrT8TY4qMEqNy5Kh8F4Rc+GTdIENCWqR9vrm0UinMwhA++X8qVXqcAAWJwb2GAfiDrq9QlrqmBxzEBGexjCbQxn6CNOpisUbT2fQB2AJ/TiY4ChXMoOlYLTGXFnwUaleRHHJlN5moUhVltv3j0Ok7NknWseITkFVJIG8/PWtXkZhv3DaRKXy4NN14268+nHb+vjYAaNGe3JINquYns+QMs2Epre7hVI7ZAbwM8GKXdTcfWqH/AMjHdqj90Jxxef36zHlMsurmqCT7VNKoph9J59SR4BL4+uKKcyWZpLfI5XbbZSZEmhJDXvp95E9RG+pslJXq7XvXZj+CystMWbRO/zlrJf4Mw4hYHakfbWE3ByyXeT2xNTP/NGbeijK3eedHVO7Xohl53HW2NRCfRtSNFQvCmw+uoxKUAnu23ey06piBKcRPbs6SW9K9bRoHE257fVhbKts29EeGvdv1oKhmK6M1NkDCSLnPl9RYfOozQEoawesEJL7UdEvJmbQFrxR7+trIWoeye8XFJQP5zy4jcnSdPWuWBAdbn7k0a+MkKDm6oeZC1GAqI5h/JCNxKEujylYpVc1ovnvi4X6reXLJFNF0OnjtPfKeNW+bee3I2jbxTV7agLXMxV+sgo2g5770yNf/l5NTF4yyX4=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
