language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: Igco0nMPmXjhJlQniEl5pESF0t70A5VQ9BugzETl+KwEg9AHvk7d3dS8r2LlOgrusBE0oski9+Kxe5wfbYTsSIRkntqFxAcSNITB/pHEkiN0MWTC3kAjNRfqC1Mw/KOa1P22jhuKJmkT8iDoRMhjVGLLo3pIR3HlturS6npd//49ZSqL8341Z+IFx0Ay8jwyYuFN3hAET3rGE/2rxW3KMxwTJmC2fhtPvfEwLVDz1xyoGhS1GZS7AZT9qf5mtGu85JV7LXsOC+eGnML/ZHGGmd1D1dgwHGqpZ/fUTWv6m2Th1ZqkN3HedZaOvOMrgJDUMbQJiBOOx5brC0whP/9RIdnQzCIEenPFI30Wx9tOCHcaIggKfRZ13UHZfg7cpmk+67AMB6pYnD8ms1CXfw/LzWiEVJKOy2fSbdteMWqP6ziUOMcnelf3iBeNCbhUdqvpJXYUCwxvGs9kew5/5FXU7ZVz4fSmQUO1t97gdouYpmsPtPDerFJQb9703N+zywJeobGiG668c+fftDnvzD5UAqlpPw8zgcRXz4flpU94enmdphMjdAzDI7WtmNYnhiSqUV+MvuezV1JsRrxZSZ5yvRFxOxHN7OA38a7gtjPHWhpsvRATznkyOBV+0ukYEqPJiFZKpFI+6sX3/1i48OSiteHdY+rdzx41XCYTOwFxK6E=
  - secure: tfGGbuRBlHTbxTVGsQ+RfsvGQfMYh1LAHdyoZZOiLSf/2biE/wsvM9p2VwFp2MQUionOKbBjHJTITcQHtyhMgkPU7EDlpWNV38cX00DcW3Yv2dxuMfsL/ZUcAso72HZSbj5WrpOeUDtxtH8Rfu1mTrlyt9wrByEXo9GZwVS++kl1qxT8TzdNSOOUt09yUn8WoT5TJw/6xAuMuNvSZoi0frZtgNlsF6fPUmMK1CqxqaIT+K4KLzJwTLfPePM2nNGG4Wk+9s/SKyl6x9n4OIWG5mWudXOhmvWKdqEr1B19tpdS+ljHYZt3BRRioQfm6eGkrysHpkY8GXq1XHglUnW/s14SnDRSID2ySSwJjmFx7Yq9PyXPcUmFM5zyqaEtoInVb7Xl2k380wj0bMVlpJ1kSR+Rdg575x4QfWjHN7OgS39GS5VZqPUC0xAYIiIZ/ZMoS6zm76hAvZoTND0+C51DrSdxTrJpuwPeQUE3BGBP64y757wE5r+i10CSU4t1NFjbhpiwmHqFFaijNT1etqZLm4kUdf2boDwl0usvDLH0vYmARIMljZgxGZZ52j5y3dyYAWQKDCKaj5doog0Mc1/RAY/j/TOarnE70oEllpzc9p8oaRXErLVJbPSSY9C1eFym+kFtPaRT4/p2RjyknFboWL03gXiYqFj/9m3r6y9pbfo=
  - secure: Mn8oZtmeB3gyvhoe/p80uG3rVcJMjWZB8SlL3ojbhtt/7sewGaos78CGuVYVjGCMADZWN9y9B/GjjvdavF8m6rkDP/CKwNY2tV/zPFersy+5Gm5ZUqWTEDDAZwZbacfi+ZZceLPfgySdQGtYcEYbY9+1WNQ8VsEGz6hXjkccZhTdUFvuRmu5IcxfbgnDWNarAEkehv/Xds0AycP0MBvQQ+sixOSmlK1fwAjp1qdsRKxTUHNfXaBHNBnoPJmqLJ+4RgIk/L2tJv+Z9oSHmaGn6iSdANeZPeBqllcyq8ZV8gBpRqJeLKQUWmdLR+UxtqS14GcwUhIeRgAyRJbHgz2rVChZuWm/4iJGxIXthbRu36LPjU+18wY7Hdo75HPFD/6KDt5GKLwazYTF1Nm4hv8/+ii2wsGSAcODFhiNgHXqAUf2tW8vsbbWHMDZ+EK2Gi92yXBm/gjFuwkPre93LjtGxkzUMehqGtRTScFBOnc+xt6BDqrWrCPgF/r2NCnzDxj806Ei0W5Q1gvHOdoYnSSAb8/SZtsBlyJe+943QNybwlWdJbBH37YfkzHXkz72D3NJYAr28Jimu2xIC7eMWSUFAGHrPrpRmj59DG88J2XBAEHtIk2+H8YunLbnmbn2GWR7G3zcvB1MFzlp+tvElWNUXapC9IeYzDCfL8BYK9mHutg=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
