language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: kB3Xsg8eAIdLwxIJXrh+biALIya34jsnshOG4ndNbljuq0IrVYC4smFg3YDbd2A+8tqqn8aLDTEM8pW5O6c2te6Y/U0ljw4c42wXrJBwk912ecjr0Gc1MByDM31VsrxMnKVNtAJK1gknajcGKxPRKyxhkinKCaM/an1mYHRKj3plQ6Ki3oNb8cbfy3qSympnzWFeDn3WmasceKZMc7r5fjdBtXnsyPWFLs6yrNBn78ep/gWzQvda/pvZplujr3kzjSn+UxBiPL9sIOZzUfFs/bUMzVWBcPaoNLS1mSma1DoqOBKRgATgajk6RjpFRFqSe6xmdozsVUKPOggZPxbDITUUCCdMrIqytbuWkaIgk/+oO19TtWtEkQfuzsE1ESkunTn58QUTDcOabMZAitYbqDCmrHPIBCC2xg9Cw0MsMyEoqETuU8Al5admCuHnjdnblGketzMpkHtw12R3u7BNuEmL5S26r/Kd5xXFn6ySsNu/8e3mkw9HGPYBSxV+SyKLvRaw9p96kzEklqJqoDt8qR+rchk3nidw28eAxBPZVLXWDJpcDS22cMvC4eWJ1KMLfr4dXAJJsUBrplGGFHdTP2NkSSPsobof1nDJQaXDZDat5jJqP3uMmd+NLForl7Lrf6EO26pdDgQJwAKntJby3icqNRgUgpyi2WgbcJYYSiw=
  - secure: uv88e06FjWxr9dPOTNY/Rzxj5yAN9kwTj2m+MCOlWMbV2j8pH6NhquLPUbb8y99TNd85Fs2MtdsTU9mLZ/zjfQlKOLYVZyspd2AaUIE0OdhCmtm4p5HLbUdUhr4PhqFFCF+A7bNVJ2JLy9DLXD4WYrtcRtbZlWkKI66A1zb/DOH/Z5lERwr8g5xqMnPEat8gndHEqaTtprTf4MB400y3NLY2FO0aw5aqhTBxFfn7zHSykVrYYTi5OiIDgSJHghG2pF7qUMHp21sF9lzqNvDm3aZovStiMatyRJgBoaS2wFH/zO3XerrWB08y483wCB5drMxYVVtQoINFEX8cPgtcjIFCqGhU3dTzBn9+AN7e6TK/CCOuuVWYi7ZA9UhctR87LXqTw8qF/XLZ/+V/wniSQ9oyp0l9rihjrGH9OldM8eOudw81q3rlhYuBvw+16rj3VpN7MQu5rr493bqjrZUlo16Oj3xnCuLpyDNUkMG3zrmeUhb0zZe5UTTX0CxkmGTKNDEi3//CcDrRm2MoQZjkPe08tAtMtNx8Fy2G3+fMXpYZe2iCCmUvfLRif9nz0pBjQTWqSRtjpGLnLHkrNOLOnmUK1x8SHwfL7hpLVNhCNIBjZvNu1Xtw0eTI/7wn0zoe8L8GmEFflV+LzU706npN7zD5t7/B3E0ouwg6M/vS91w=
  - secure: HV/dOvx8/SA99aYtF4dkoAX68RLVDbhQmaKDntlbVhME5O7xkSqD11PorL/IhX4Hv+VUPlIlT3gOkWLB/etsjM7G8lduvvFwYuF+PC+rmWLyxKuNmhkYhY3OLUps5eGg/LTL2m3johNCeGBzb1VzKoShoNOD/a3r5mM7O8ODIETb5mC647pRkjjc+mG+QGUL9l07roVkUGd1lhxDfisC5V4Frv5HpQKxGhbMo/9pxoZ+jw58V8WdWkHRlSkQzfeZvp7eeJyykx0Ridx+E7x3HsbrrnPxGhYMI6UN4ILGM4AAnZ45sJMH1IgVWhCcxIB/9geoy74ohRl/rBKkgeBQ8a36kyb9rRCKHnFaV4O+KeLsnfRcvAL8LfV2vDSpBhdpFe+hE/gaULizaZBbTLMxBvxtfm7lwVotgckgDSpper2oGTQnke7aYrUQvR5u2epiY8I9/FwZA9aZcq56vbnnAu9XweJMf2j9eqIaKjT52VyYjaUC0oHEDx5fZJd8Qh/I5UOra1anu+CIRvMOY/vtSA1lqtwfJePMPlTVpcjVUZh5m3NM7Rer9RB7KLy3FOoCZy746TKnW514Qd/QjXggP643zYjjce+YhkijimGRKSSs53xSlydGydUevLvsZJdsFPpnFqRjZaOekN4Ax0YQphm2gZrxHLDAhTO6YfGuK7I=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
