language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: Cy7wZjaz2mApE6ZmgiLJ8H0Wgds+2idItMFGNt1z4YEG0AmJzC5MQEIRsmSJRK+y0WxzC39C7Wsss4TSdKAM3Q8h/p7QVK5rDXfCY5/wiCu9OIbP+MyduQX4cXKFHRr61b/l25PAN8LbvRw9lB/8yzYv6QuwhXXsgAKb6pjrekzEPMYF/9wml5vYJR3AlYogye5Ha10BMT+WrhJ0q5K+c9h9UkXIZTZeW97lnT6YTv0r6c22wgQ3e9BVou5ZNgTFgX7blAToi+AxANfL21j0cUz1smbMyz1i3/fEE9uBiZQ0ro+tjujMYbGD3hY9rFjnIGTbSFSpSJbGtxaf4vJiqUq0wA9u+xS74SAoqhyHLO8QPd+LHaLGaSqUYI4GA/viaz7gXjqZwtDR2suEH2xHaRLwkF1+UlL6ujneQNJVf6NTuq/iLfkuodCa4vYZJ4l5eARMxyNxXHC8soI2xKMiormbwWRUcWUKiG+nO23S/gFVaeutWgadAI8GshBVzZOYePRWOU5zDdGsi/3xVQoAKVIzga2g2PPEkTCKuaDnLoevOH67/gTwlbUufm3TbEIzBvry22FkBv8KwWbdBNo12Hg4RKJSuEdrmEa8jLXMY9B8gW4y0s0vdp9KnelJN/rsuvNnaDcg1fP77LdMqpEZxWK4BTGUJ1CVo4p1v7caGUs=
  - secure: FfcD/1pVlsJO0QLJRcN0B+tKWYTkH+nW2Tj1p03/VZ8KKE0Fd1UmSk5kW+rh+cwc/mVJQVO5oYGMyMueWaHyhe3bQleZXEsAlOlIsJMO3EsuGdKzRliAnenKHev61W/OabzAGlQuh9afrENk+qZOKLoT5ArUYFN8fjVo156SbQPweM9SRvEDWvNnSyGpgB8a7VwRqRCpc3NgKOWNbA/4N7LG5LSNFpjQawywcN5Hm146MSflEjcysSTv1skg8Asu2uIqM8xgv+hb7rijkOxbjUQ3ApwTBRh8bo50D7yjhi7nKCSKheBPZAUYQ7ixdhC6m+wuKlT3PdWc+ixN0sm6qqFuLzn2Jr45Ny2ZikxquL04LnD1ggq6vLUBwxYUEgibs3Hi8N+MDxZebjEdTlX5ATIK2rJxKS6ZqG6r9X2r8t7MNPhds/8cbutKZW7SDfgqVVg21AkmMSdbZQkOar8+X1phmLq0jSFENGrbKKTW6nxmZLNAlxVxRDUZ1oxtaPnirwXn4fl53UbvWEY2763Ab2Aa1OtcUjHvsiONBoqmAFQaXquxIlqQ8UD8nvZtrIEaxAcSPGZikMgPs8wceY7VeNKh99NgcBeu/sP5SA1X/aF8pXtEKpD0jZgtRC1yMBGX5Ah2b7CfglJx4D5EqgzNXP9GIwaVI3sLy3+lQ9yt1BQ=
  - secure: T43aLUdKYjZ3VI/qx1zXTD+Q3wqysaZ97AZtgCql3dY+UaqSzETDdhTgpckrQCY/cVWTWWo7XPCAeWx9Mq7yEFpQ08NOHB2v7ueF4TIdhdXA/pIfelcFUXPTf8xYsuTLjMfLhoH6ORtECYwfC55Zr0W7dKw6dTdn/ejiNKmpZvKdL91AQNSUbLC1UMJvsLpcv3pxAU9zeaj+01dLcp5SpyQDsw8m1zbIohNJjNQxCLyLo7Skj4aCSIsWLoB7usKoxo/KzytuV0+nPSCCDj3KsKJINdHOa5/agPC1aleNpgkSqMKC8bEqn4EO6FUTw6XLfWhDOd9EkpmSDoAmEso25xHWq6EbEGEP1fVh/Xvyr45jnkBoQun1aARde0CzWwLda0+7GLfW+KEk8RL1t1yOx1vnTgsNC0qswPGmi8dnJDOc5bUaZir7SRX0piK3q4CTh6nOQjGd/HBFTUY0A5mGMaVGXsQMZSaFlGPhKXZ98n2sycd2CusbsdE1uvTiFVdYHvBWVje2YpWlBd6Qn1pF+kn4VN26PgDnu+6Pg+i4kalqm5YHsT4UtR0DaoJG0RGJ0A8mKzbkYmGE6vuV04Jn/nXku6XfnoNyQ5AVTpjcFUz3s6+W0FFqhl6KstEgr8yDh06dIML7lGJCZo/jbU9aL0nBzTYIJ6vZhKJsnEzOvvQ=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
