language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: OlDezoMBxB6vq37R5xpotj6q/9ExFnzDcaSekGO45QfxM28+Jnqt4c53keCSJ5jNLhn/iVc83wOT+l7Mlmmnm7b7riHe+1vxDuhkTtJ1tIYmnLdxri1w9ep+CwZ0moTQw93df6a7r2vbdtLtAzwE4sJVurpdC8Od5WqERoxVzTfDvHBK16dRGuyvILXGURuuaamfC7CkgkUc8m8iU17sNdRhQQ9AqOVusSJdWaa34leW2g7qQmxi1MD57lB38N+7Y7S5EXMRLfOw09Suo81afYggkbV3LyO5CwhOPmdRplDN7LOKuZUWKDqJPwDjn4/ZdQ14Z2omLLuV3SiaK1M5/DGbm3Sbx53F2O8MldQ/DH97CrHZFjPwBCQ9ufMNH17gJSTojujOBefRdMvym6vdZvrA0c/XnAfZTvN5uMEGIwIWPQCvYC5G40JqeDdy+DBttkoyAWc8boFJU2LsiD4QvFubyJp1ZcjC/TDY6KN1JaG6ucxwh8wvgQBoAOVxBV0H4OeOkRTLhB7zVzWqz2KSe2osmviLoygPojlyvoA0hSJZMDSrbUz7Th/CVYElDGQKO0j9/fiDnzSWO66jQlbrnxsP9uSeLUq01YOYUtVYwaCsehyHA0SsFdcvvrOWVRzlrEsKJNhhlQgN9EN2NOH3Wciw1GopFxAwaAEX8qDNiOo=
  - secure: Tf3AzfjDeJZFAOnt0keWBIXytB+7uklQleiTtXLm8jsCMEKBOGxIu+EGq/PuBEIHZ6IlQZngAqyBTRG++OBi6A+7xBVMSaRQScD6K1dSvW/dw2qzYbPezhh9JwePJj9YVbFBnDG/7uCPfrtSpHmVXFUbeZ1mHzbRFOXnPwD/MeRJhcYWt3ZHzXV9qB9tpg6VjoJAo+JhFpRVYHRRkkCV+V0eSTdDZQvFMkQJW7picNwh2Xlnu219BmGxgoRUZBFkATAJ2Rqz0YQ8ujnVeBWkuOL69FP+X2qAevXRTfgnZQucso9tkJTfb2Qzlg9Q8JgMl7mRJKkhc1dhoKnGLMGQZz8+3eONL2eIJg+bhNcbsnNpe1hapH9hTKafL9ilGQ1D/TscCWdVSKRW7oj+MNoyZLgqBElc0dWchhWwQGOeBhudaZanrdAxJxZjaeACayw2xHxHBPHng74iviwGOX//tqWP3BErXt78Jx0CwatKLFWTKzMP7M7KpwMApZhH4J21qKqWf67uVdXEGGg+C5tcr3LwqYNoF2k4h9dYyl9xH8XbvYtwBUv59ZT9463uX23ouFyPD95HdUoMyYw5t9biMMPS+Cl6foYpfS64jG7kspAK25Yi/a1EUx8gP/F1FYcb1RMVflZsVW5xFJoj12QJQ+7ov6Xp5cs8DZPvmpkhX/M=
  - secure: Gkpagq/Q+5SA6IXRlkR/YvzgQJr9c4cgaFSA3FQJf65hzGBdudR186tF5P4Ac0zMwiVzXIKCLMZpGUjB4l12QP4efXx4BkAOuR2X3PnuB8wEdrdLVcawQKhdf4L3+WNeh5rsldsAoEcMZFPEgvVJwxQ8Byy1iaUme1Xyn0aSuM4PrfZ8isrAnYGNwHkwQBwKS7PYUkE/EHVukpjuMwTxKUfea72l/ZVSwKpoF6vixwoaWxhSmmUHKXXnFA9nU8m889dEI+YTQAvnGKXWMVWNfa2Ygmv6jjxeKZOuer7V/so/ORJ1xPMrzPJ56B5dBmMzF2ntkAp3Ai0H/n0RgczjsibEnvP8rtgu/4FIb/BxrcU/s8OjwONIm++7Y8btKMcz6yeOKc3fvZrJENDgLhqLeh8Kdz1QleEcP/OO2gCRHcHx/13e3b0VarH1hcBWcZSxtspDdkk+zbaKUYRMSQ+GToUQKFbdZPEIqszpN170QOlHfVPjTg04iZ46FJpE6w5LAHWtv+vw0xMZ0XRrVjuMwfZB5xnSLPIe5isWqxnxh/Er32vu3LKQ3ELWVcL00dhf6yWGj7CizDedMDQRiK/8plaJoQTqS39mMhW3juYGfqwr0n9BovYyRX0zOzFaM6//s/+2Gj5kzF9b5MgRl7RH9KQbEcp4QSbjJzyJgbnLV+g=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
