language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: PhJuCrynPlzgkvpUE1NSpYh7D9Eu9Iwya7gxPP7uFigZE1vg36iZmGEVZ1EdOzlBGYS/Fx5jt1fPRO2p9rP5R6P+o5d64qMZmp3OBRXuoxrBZdJ2lURUZmnKvGCeehngHuFd71ptn1jugpZgYghhESPoPPAMe3sphttU9gH5p+2CK9Pl4ZUTg88fW0DfHZHhqjqcESIuG0tumpdxrG5OXQBUOWkV4mp1oKahGmYtVv7i9jlJdMm9RaWKcEmRuDpObJ090ECakmNM98WI/nP6XfpN8ViIr2Icqkr/jHi8KloASZZ7gQvM6Qm1bb2svDAxlgfTl2sEhdHmMtSPbTJZHlQIvzep4B+Z0KqVL+HQsLKq6MicuY7PQaw+yE8OdC2HPifwe02j5aDlIpRI47lYLLthuV802zEEgy7OWREf3YADfW5uq8re4P9lAceWZWq8ZkS8DiHE4goBtJfoDBCOPQcq9kBdHi2VW7UPN1zDexmGUL7YudwSAtHl8Aqsc7NVQSkfJBmh5yeDSKYHInMvOJ5kLll/Bo/44krAIpFcfJvfGz8kqu6aj4rvIlQoEoVAeNWjE/uCz/YEkqEisCiyYyMWdGUIRA4i3SpQTSpFiNfo/iYnoPBDNUoaylDHXnXgIRMpR2pTQLgg35oPBERi7D6+NfStO3IsAgrhDD7/Tc4=
  - secure: WDzy9D6j2LiZswqgvybGlEDRoockUEyTE72Zqf7sjD6IebWbeJgscncOOE7za1M4nSYUV8ilAzLCu+7QJiqMmi+5UDZFeb4tLpzVeWV3Q9DXcnLVw+4YHK77BGMi5ckYTSZwXqtmcBbJ+b/R1bdQc46M5+NHFA4onW6I5Sw1dEwbi4Na6XlnI3Rnhw+uZ6gNv1qYDCOPJPMkoJ1t3LjKWrpziiJ+qwyV9uQtVR4g56LPkzlR5t4eUPqxRMf7+WtKn0njj+KJ50sdlfwkBTlQ7PQW10A4EFy/e1EbJs0jOvEG30htoQ6cww1XdYI5CCEBb2cLzi0QXsE+2ioaHIVpC+sb8HvL5tRZU2wZs5tFW3AKor2jnD5HZ1EEEoMTEqUwQlTVHnPoVCI7O9PGIkZiFu9Urx1ieUZrsr7X6EXDKj9jJGytmIQytCxx1WONiB2MGq8mOgv9ZWNx4JZoY44wddFDhe+9Y6sw3hO/XVYMYkV6lihZnvawWVImKYzmOY9pkTjT2oyCzkMmocA6cb7HmQLMvwt1oqHZjcVZNmUuJYCLwTXvJSXUIBtGn8mN8lJ1HSRmnKxnutY4PP374g/gj/1cgq2InYL5rK45SVJJZ0FZNGMoOvumNCiKlbs4Z0YdZ8KzFx5cvIDqBV0GISJQzTVR4+2bBAm6Y6w2gxv1tnA=
  - secure: P+vrTqWi7oJ+QqjqsGvQD/QVfKp1Ojgd+arFLIRdV55ugGeZ2htGbZtEZnK3HM1P6CnPcdb4zM6ylsldpUlXiY95+FbRXBfHlPGjw59tQ2zDZSHZC0PcHFCoaDO7WUAiK+IfzVkpe5GPE+frkQwEHoiBnRtcE/GLIiCxjgbh+LPpCv6h1hBTveZDQ9w9Zanedg0+rAhmi5b1lpqoYjB9kAX9XtjFgx1qvgGwbYL9GlddUrEWjUTV9sJS+JpmrrDP+YxLMGkQuuwHjiKnsH8vy66iaUGHGTm/78gbiX7s419iH9BV6vuKlFZ+gTg35xw0T41tnoK3dSdrXnLSIUwTiudMxW5hx1/16P/d88v/RDxMbq/OjFaisK5xmS8ibWZ+V1ozTF5zFoRjeQQV3AH5APHj4KsxRRjUadyLGgU49hN6jYatPQIX6oab/D9E5ynQq37ttvjlXTNwZnLlnu+LURSzcFe6QgO3PgkkYsDwNv4INOdB0Y9qK1R+Y/9fIvvfkmLGDplM9Juo16yVkv6VaKqtHMGAac8mwNasYMfRGrQ1TOOkSeinu83eJm9SfliqGAa2A/P6xWVNuGqPJ3afdG5Dj2Tq/TTZ2Roaq6zNI+UKBM95TKp1zPix7+9L4ORwGQhMhj9kreF5JHZyYFjh9HW1VZQv2oSRabEJYl7OM2g=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
