language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: VRwBUy6qBAGXVXUqgxcr/f6G6ScXYgOXYETbeL2M+nEJChF2MVdCygtqWtnChhq5MkEoO7QW12nMArCDkYYXaIuveGmZ9Nh9xe+3Fm9t0y4uJ/kRmMu5TYmfYCZGZuXW5YNQTBJ9EErQ7rq1cyE+5B5oJUU4uNBiDn5Pu69hry0m1Nb9iXwVGrnMimWlL3QouF74qOJEiwFpsN4RImHhUIs3mtg23M+IXKINUUAiq77lmn/R/tZQV+xABfxnuFruNLbXRtGfuylKt0hcEeSRjWmfvQJqzmVH+X5uOm7K6XmMCedgEhnNdPhWnZaC996rRnxKQcQ6X7CJ5gEsEQX39oizbW8KqmX2mAaXv67FKCkMXbzY91FupgBybwJSvrDI5ewoE8Y8DQsMhKYmhLeRerkK0N7gBOIMzq7dMjTHb4YU9sSkfaE4M/GMD1UdiQ/O+IY9+ztUc3dxVSPLO/GXHG+zYAX9EN0x4nI//gT9m4GwlzbIi+HWUdRvaMbgoct1WvOYWL/tYE6Db0rJGRoG8+ZKubmHPfQJENdTCfW5ePaX9zcB2B1JNp6TpRX3bOtqTubbE5dFnO9ouz9DftzTJMCjsQ9bT6Use82a3zNMTexu0sqJRG1MhD9vVAOi+vn0M6I5zkeTo/U8Iv/O7fEoxx2P8Pm2jc3d1kfHcid+A90=
  - secure: r55I2LWmxi8l7sMusH1ZFuAVXB0SFZiJjBRuRfCKXhoTsSePJclBz9n0x6jog8ptL95lFmAWTcddx7+aHOogYVpoMI/5tRqEEx47nZXT11pVWuaxCrD2R8MaQhWP4+CKOCpr7WLmN+Ku8t85RcmJ57rb1gUdwWQWXQOaMzEeJm81I4TETF946As8moSuOJax8cMx6wweuBY+zrkEQo/rq7wE9RbILsF34rX+88eMw4esktJKX88FyJ7UhlgpTZWHjcuXCiL18gWkJ4qbIUJ6mxrQnv5AvfAjbuyZ5NEZzjZcpItrJC7SUT68fE2zC4oWX5Cii/kgWtTNR1DPHxu970fh6QLzs10VxKO+jDDt+I2KANIsJZs0XyOaWpYr5v0wgNd1Vn272qPm1IUfmkiMjDPFEqaoxlagkRBdGuh7arb+6JioNfHej4ywfJQi2SD3QUmvSgkOAdKPTM/UN8fJRMsMwUY6wsIFlWlusSsULloWY0MfYmN6q+WgcEkm3GqLWRgxMrIFf5z9QrjoQIpsbpmGdJXoSEAlfflgl2lrBAfcKLGh0qLZjf6ahhXv0tTTHVmWXLtC7o4tWDkVlqofLPM7Zm1l9LyRAY6ev1hGTC6g9/7WfiiIzdZtWpuZslovYHBYePgqvdjVjU0vNe5neVrKq+EfYhYliiWMQ3lLbLo=
  - secure: GAikT1kno3V3qMIaBWwinlQ09tPkoo9eczOQv3G4IEQ9H4z7z0d1zMkdF0a125Kn35Oo80LMsfVXxO0l4BvvZQXCGjDzxGqLqBPgOloEbe+lmmXxItqqlxW7ta+D206HRHbVqQlyFaVHxOMjgcbhal8lDByEUZpHdqxm6S+OvJZxPgrqz59SypJbuWyBYBn66VRVkk0jij5VjWm4GYK5mdL6ipPR/cHweFRZyoYNyxYwGlvCtCfbbEZf7JDU11yYJYCjRw2NyoCQpArM60DfIIoXxlHPv0JL28e3glFE9WcdNAz39Hi0onp1pDvqC2c3UMxea/41yikDDHVkMP3bTlpdLJ95pCVXa1YB3LphBtp3koX6VnbV4VkE+Dg17VMiONfelnJhuPQgzM+BnQrEIhJ6HwDDfShs572NOPuLsLbnoDZk3om8WGtD9FepaduBmSldQKlvaau47oybV7W8v9tDrtwOrrQLKucu4QNoAD1alLWcnFd1o0aHJM1Fd0Naum8HwxK999wbmp+JCs3sFqDPuhfY4vevF2Vft2YSw3WufI6JtudIHdHTQ2Smo6xqjsEOaYbAomAb0PCIx9Zc+mY2oe0OX3kwnpr3wFo6sC76rDYthYCjgSFiuZaznGPA0nWjOy3rDA5zFY1rdu7N8zKtFo3DidP+BzXzVpLXH+s=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
