language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: RRMDhG+J9YAOFDIfLJ+KAAdwlb2Uiny+vrIrTlAV049TmbPlsgZpv+v86rVCIIXNe9qCdoefiHhS0vvQ7YTAC+4OLgQdYXC+Y1tNHwroWPSFmNqmqW1Le21WRIclbsLUCZyN0PowrXwwW9vgYJMFir9sTyAQIrqDUKDvmQcTT9rfMPijHan0c8LXRAW3Ex3S+yzSL8W8KH9y50hv8zQPVdHoMEBE2a3TqFZKOlASYRJ4vRDTcHCO6yYrPyOA7NZgysQdjdYiSEB20ZQ04CxotLlluvwtRGDUoo5a8zcBHsT1zZ2V6tu7zmx+zzrgmn60JF+3sHOIXsuPNrKzAv415wBhUu7JQQLJafxmpwvb/nhGdkGeWOQzXJFR03dD2okmXsjh55jLFDchS79qO9F01H38hnb4KvkUEhCqQJml+8m4VYKaJ0MeuPYcuGR6HM5rUwfirK3sbxTjuV3aYglJ1dCJ9rgzCRLqq4QuXtiwtUPpWSQocuFFPj1WNJdy6xSQycoTy6lV2y32H01rqxVbkGPbSBWB7mFVyei8tRrLRjSrs5yxSR6Wj1fUkgceD7/jE8lK817cFe4EVwujuJa8YFote2StPIQgZDj1jKPH2+MM+9iKyqCzQ6cc3m0gviv47N+q1xC9zmjKX0yUNKIxj5ejW5vsnprhH8sZrEM+JFU=
  - secure: EQgjwGbwypdLll37bUnWncCN4DpdGiraM8QlnBvbmf97VsTz9cS2wU/7pBTWcuZA4aMmmZToZECnXLgtQSDCIIRFQAptXiyALMWMgd7LFLoJSPvGqLT5H2FGxjO4NvPxzVJlpEjeEHgcVcuCzJ4MVnl2t5+MTO14JFJ4L6G1Mtdx/jl11CUqSZ3bkrfCnxdhnxNT6oNx9FxIPEpTGt/zn5xpMx/Ht4pk2rb55nqtjY6pDdtT3w4VSoFOq7aDChOcjbgwCaU6IfxtQ8s0SMetqOS5IqJYhWz1H9Y7BtD2yL3tvJQiCuZq8WMzLC7FsVSW481KzS+drRj5C0zpuatxVIuNtBSAdYNSpmxBoUY9Gxq6Dnx4lWzR/+MMQ93pLlRjC1xjow+ah+iAqY5E8+2RD1w1FPKqzeMd7/QAevsy54d6J3R+YucndSuQDXFjnNU9zQ/0K9l5QmxY7J6X5WJik+gixPcq9eDQF8uNA407yIw/iZ2n5mmZHRxiNtceDXQNxrzOo/g0znHmSGugEeDxIGJDSBwjLd00bkzUTOAkFGkM3C7nOSAkwJV2TYzrqftsf23rqDyfsd/ytrAh/yGYhyrFvNLg24l5/RBhxmErWqxepPpZE/KJv732iAh67mVitck8M2B2TotCwnj3RyBkzDkDu7CHbDI2SnfHHOUJoOA=
  - secure: PsakB087++vpdrLCMD0xPythU9zxnN95ayeKVxD64rIW3AUfDuSbiSQimSVvqy0aI+y0GLc/mqLzFs5GIjP6ahRhJaec14q8QPHiLZNX3jZUzf6qHmWkpTjjFcpertYnIIc75xqdPieRcfOEdjOLz/PawTgWoMhpj3aURRqyhAXWW53sKD9YPZwdIAxg2T7TF7hgOUu4xAYeBwDonYTRSEv3gCCE+X3ATxt6J8raEPDbjqxpnGmkNqrIulgSnSDeOWfhIbZEdnagL3tRMPJNQMJKMhIu/A/vpuHg0gcBt84G9h4k0uBlnxauUMugOaKzSiHyZLDULy3dHgIRV/EXrooenZECL0IuYkkL8onVZJhTiT6GCFWLfR+JPyTb9Pbiwx3sgb6cQUaSU7d9BCR4z1CUaWb/vKiFT+/msUe5GJHda1DMyMoCjBjBK5Vy2BD57B4nnyaFeQDooQe0hn8/siYAwuhXtTdFvJ6CD2VtNp3qd+7whSBwH8DvXoFnwbUQV7bPvHodxb1zYd+3sMQVbNWyLz51ZZrbn/aGYig5/Rcx6qk5+5kzj1pwoOaggth9m3UAKL1OPEiYOp5DDAIHpZLwPfXbtqLyKnIutyju1XKNOnxFd1sEu888vOw3Xs4FJJ+NtablYduUdC5TE6jtASUBGIzYHkprNtgPkhar/HI=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
