language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: ZXN2IBhSy+xNZsir69CfNRpU6cD+ujqGXB5sNzR/thR3oOecvq2IRenRXXCDmzxuy6JZKE1ThUepU1h5cUAZssjtFalHEv3109kBzhJ5nT+Aoa0fK4NLT+kgkx3KiIYmAVPQ6U4UBUYh7wvDyLAnt2qdVg3BioV19ntweM7ioJMMuQUa6QhP8wIseXzkDC9+CtcW92PTg4yT8hb0TQRxPES9eYHpg6PoIQv63T6lzxSgQ3m1RtK97FxVq7g6T1qQ2C8UGg5EfOTvPY81o6n2ps0ZEZqUxcDPv02fUO5xMnz0OfN4UQIvZ2M8JF93TpE3mmOf4/oEj+cDm1Cy9vk2lk2URjWhc3T2AEMCHXxCbSlNBCDGk87VSuuMyuDGcM5VJ+hYgGucnVSUBROrpq7SFdGA9sKQigZcrDAiFKrtoxnY885nApZ/Xa1pHNZZJnDiDPp67lDVMZlnhatzOAFGnxARxDOND7ry8MFyfsLUqusuMEVYnuDvVB2CNm1spTAeqWbgiOOxvJoLidbs1hQ36Y+6ruHy3Ql7LVWc4cosFzFngl7t+rLdMmnmwTGVfujBuzQ29a3qiPVfvtGetG7o8vS9myrHLdFQ8laeKzYgOwYoo9ckqcXIQL01Sj6NcXU6RNMC895WsAywWnYdhHmXBeAjmj2t+o/RURbgZzs++WQ=
  - secure: JXgXgR1PaKAY0I/+WDGgT3bI1bLuc9HR6BYZlpcXcAunLXV1xZjyqJajcmP7csEGOJ8upmolRcp0auMp03o60TJIX5hhyBBR1jPHw7AJqSWkTXscy5+vysBgRsaPHd7E6UTv+CaeOQf49ajWGwqOHGU3YW8uq12T3kYrDc4yJAHt+XJ9EjgPGih4hgLu1bF8dX4kKEgHidM2S2NmMe6zBmNqQLXVBi3na7FCUfqocvC5DItE+Lnxgz47SFfvlAoWBrmK7dMa5pwuq9JLBxsU1l2sB2EoOHW/UBb0zQBft1/MlIyN16PRNILslCU/ZRp0t8VJqJBcSVL9CB/RMXSxsgYiPT9bjuvJPo1qZFsAQtUQZw2PkDM2oycuyAe5aKjItzxfVkVRVk8CXFBc+4Hc36CYMok7G1r19CUygFKkwyqsEuOlasBh36aD0MCwTJrMehTn2M2AX97tjVfP9OA8nRODdwgBZJreJWBMKB/2NiW2JFlACeAASHbYlxpcIDHcBbiRzv+7wo408/6zIIZlCCymCdLbPUdzyDNjQ5hci0bM6bx51lfHkL/n8zVeFcfMawYeaUA+/QtLR1W40OiAzEotTZW/5ipKuIEJq0bxk1DNQUdrNYt7l5ng1xFStYeXZw5/usW5rvMXHex4MCuoDpxPTGoDmgeLzZ4wDPPnQb8=
  - secure: fNhYP/9sCVs56u3RPh4S2g6QIsFS3/GW0S+O0GwEPgbPxzpQS93q66vBA8HaBbCTWs7gVDxmmEfq2Zp4f+RvC47BVGxpXPJ3TFUE+OjkV12avQmiFZLCi7TsRT8l4MWTg0blzUYWOkRKqzZa6zUKDAopWRYH+5woNaytBieEPpvGogeogM9xRXsxZ6mlaBJjf8jUdFoAZXD3REQkZQD5onuM1IJ0B/GNysheaoMAvcy71LTGEDXC42NhUu+3QNhcRG8PITjx6QBOMuFcKfIWjm6PjWEYMUJ7QR3sCTDP1tmIBwgst02QqD3W7LERDSlJHED0T7qXJ1JDKXfk98EeoLCKL0XnRPyRzcMGzgXfBdVgoPRPikt8szeWPYWJXiQcgaOvTPLqjvhVSkB6dAANWXil+4cAS0f2s5lpJ7enCtHP0z97sFvTeCGoHbcyY0KUK8uaUncXHdHKsSkE4GFeY1/oQ87N7Nqkwy1mvphncITp5i1p9cAK45InKHHm5h82uFP0FW5E3FSK0WOpH8QD30xcEahO+R5clbynN1g2c5Fu2grkTz+68ZzUuaBW7LB+LLVjFQdjxo01M6S7UwUeWrX9rK1sLLkwOEccY6TQNVoAo1gCY29BT7cLrhrFbTZZzgcaQcNHieI1GcdSWtcFJUa2lYIgWQfGi72KX2pBdk8=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
