language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: mJLpTNL5tr7msCGfxD5CgkboObn0KWa4plYH7kzYiK5lW8Lo8OT4PG7Qlk4+15dix5BdjHFUgO3BQqTzy/f6YdAyWoPDbvg1XRrzpxevFUVsVwRBBuj/q7Jff8NVSzO+Q/JplpJiqnPOF6MI5DKto4fzf+n53GorXyASMOLzmtLxr3qhSRlnYgHAci5PMYFHGMP01GabnT8hJViL+Gi8BC/d4dMOBH5AqDBevaYrU0AhNEYKNc5e1EZmXOYAB4094Pg457Gn5K1Q9nkYegag4OB/Lp70yOpknSEsT5+hO8+X2zp3yu1ZY8F6WSwBj4Oj7/dN9w0BEw6XjKNCC3Wl8uB7LeWZJlpC138Wy4j9MID7oe5DsM0iLOHDQsKJY46xheujBw+dXByX4NDnWRpw/oy/McnecPPFT0MaZi4hfAoRiEJQjDL1in9R+oT274v7tLLwD/GbVZf5numDTRVsOn2VGwibvWh3Ueo28xlYq+6m8FQbeUFwIJv7B8v8AqtxlpdJAAqX+fVMa1PPkQuEDWt3f2NXgNjzTxcgvSQD3747W17YHpIaROWGtzEVahtYZIPKHfdcJ53xjl+hu8tnRKwsubempq1Jlr7bR//tONRieD8btLI4N8z0QlLmwVtUxlX0S6mmB8ju4MPKAt60sTSFhTRjwwRVGrzDsMycEPc=
  - secure: XcH/Omgu4lmOeSZ5e3KFh7Pl5VAEnkZ/W9tygEDxGWoUB7HOi3tWFl2nsGtbP9mr/KKMRbeB30gt6Z1bMK9iqDxGEs+6lvPFDkZ58dD0yU5dEI9c7ZwD+N2y8p4gohWNMqEsfZhXXe7p0jiWi6bIzdkqpn5drmyEQyIx2u/PNLtVqOp1XAQKrYCwDz55wE7EXElGLMt1+lAtfU+j/3mbvAjaNjsdLj8/gn/fv8C/EHxaaROE5knbP+zkLFKeAvT6G9wV4jetmObeTmFD9Ymd96rln6ZZo7gi6/BLXp9ywiRJSKeM5Rq2xP9A00xnecmDOkENsLL3wVJYq0iqVxOIfNsO/yrlYkcmMwAMONxYj69zrldQhNDddNOM7vefkvSkIrjbVVnKoMBCbYaRuHDstKiJaspEmssCH9ujAGvHX97hyhU4FAV84i9V8gcm++ozhOtATu9HDntE0QnOd8kqGHcNsAbY88UQLwrES1UV++yjFmk1RprKzDAY8+Iy0BBFCaJZTfpZxP1VUnSoK4VcaY5sEUjYdV+ZRxXP71nTozJN2sCkgYvyzaemyp8lfhVedgEOVo0zJqedMmRbG2qyKi5b0Kxq6+d6oE+tEMBR2N3kI4gQXuzOH1iynSra3ur3mNSIjLkEet+BF499mrGYH59oiuhrExe7nPA1w21NCtU=
  - secure: eBQpeLQyEanrDgDCowsHxrorW3TzGWb2qGI1DOS0lEPtWlJXC05cf/9uKpqvaJ2b5CbF7CHU8Q57/nqgrf9QX131g1H4xrsXIELSejkdpbJQqlr8ws+LAsfeKpsPWcBjxkcezK/oJnwOZB6eex78hkSZ4yFpxBLuTmv2VezeQGk0BN2l4M3w+OwYxk5yclQBPv84NAIm0kzWRg6rWOkqcJ+RJ2UwHOABwAQFH15eMcdWu8/Pgv9gQOpp45qU1Sp7VswCJVlC8yRiUQxoUJcMn4y1v6223R+ZXSNOn38kreOS9r02xJ/PF/sj42tfmNG0f65+uiUcYxOQ3Gtx4nFusvqZq2/8gmGRUWDKIvuaLCyNcP4ROl5fb/xG182FlOQCUhr8rXUdZmLtnCbszuj9/YEtyVmbZuagyf9uQ457swcBSevzhcSr5lP9+1nYCTR9Marcp35Cl0LiU1V1FhNZeIftS6YZ8i5EkRij3YXP38PJ2aMN9fgtqQmDKyTTmnYUYKp20d2O5Jq/wNTd+VBoeI9yajZn5Xc3A+3F0GhBC7bgZvzCkUU2vcwg48q2/ZWizDwKK994Fs8OsNawGIARQ0ZaG+6dmQSHm3xJjH+NBdggMQrUeMibaRLrrEgHACp/IxeH1AnpLRyWWldC+R8liNKJ/MQuRlGGZ4pbHSoTUsY=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
