language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: rNDfcPLWU/97Cr1fobpsx0l1lFuoWnlkzxF8FhCp2uBIqEzqTkCg67WHVEREt357PyFBD0lHe6aSddbv1nNJuU+0lxfj8aJ8vTx59FwMl2YwGx4P5QJ0Z8ahd7eQrBD4/1kn7Vslto07w7U8etoTOr2bFFpAFT0O1B96TWU45p2aEC9tbhxPicj7asBgK7xfwfDYVdPwFyqdfpFnOarigao5tGS6+tp91hsr5Ii9zZNBsOEJ+URmOyvgQer4QOZAOH2R8GMzOsKU0WHE2/fQsBOFn/n1mhjgg7e5TD+zwRg4fUseeVsq8cClz+JFHOp+JXpltKL8bzPiyTMGIHztugG4QsYCA1yveVB9r+kDzYmqCV/oKWLMGvQfQOaPp/Ely/s26xpZ4R6tgUOw1S+zTfEF4j7nnPq3bB5RapZhwKcjXtkl9gHhDdK8rINi8kdoT+N1hAGFaZNwt/sEhsyrK2SmoUrJMafen4zvrPRhUirJDHTXypgbTo0RKPV6WGJhbzMLujO/cmXX3ljwMTTRTbtEO1LpxClsfxgFNLNGdqrPOyLMHe8FU7XgmCamNJ96AfKxOnMJRzGXAR5BIsyZ0w2EWN0TsKaRJy0W1b0mFRYeBD96GEZpy/ai4/7hSD7MqrGvug7IuzVmHYGekqHTX0xkzco04jvdqrID0z9adH8=
  - secure: DKA81FkUakGubqZjaJ9A0S/F+sPOdCzyVdIb+q320u3hTsyA6Zg9mzWcM0z3mt7eaEez2FZquTT8SJp/ZCAJMNZ2lMcmZMitEf+ofLaMKuaGB0eUIUlZ68pzMzoQDgb+/tzfuN0SHALoW0K3mn6Gt+mJUJYrQ2ybqjBqhXCNrSdORaUFAEiFW01VS+uGWKEdoDprNdahG8KjGWxT7C8xoIOi7gula1OQjU6K1ao5yB7Zep1+vygNTuk1EXp2MK2aZwu6aDBTOYvnyBoCEDW0o5A/mHprHabJSU5rnehrNpjUNByCFHBr5UmaGD38JAmfYM8Doo60zekpdi8FZ/HCcm/VnDhxQX7G49josXA9zoq8Gk6dIMQsQ5if8RoMe9sfIM03YqF+HrhCsxn+0nvyNLQ/+Gk/CVm/nEgl9O2U5qzoYmHYoomcG0hLCsqaLHqUDkWKkYea9TY/lacY4OhULb6eq35eAODiTvLsjp63J0EC2q4BIuSdmqcfcxV2+rVjvtkuHmFXrr41paSoTrgFj3k0hp9ZtAxxmTgdBKazDO/x0gWyqJUAE0QdpgTuBVFqPYMIeyO9fXheYCCBlp9Crm37JyAFp/mmjD2tkKXkc7KxliKlIBP8lDYW5122kgTg5Pxc8wOJX6oLhslqVq03g1vmUjpBqK3lj/ja5Oq0Pvs=
  - secure: vG1xyx7LDsRoRyodJd3lgu3vQEMkckcPNJqWFpZyHBqXNunUwhQMUmwt4jZ/6nRPjy7XEWmZhcWFbJM1mEqIoflPgSlFMOmeBsr5O0VGBczs9h9SZt/aowv6IQtah/tnX9eK1ufgtrRFyEhKO2Gbod0rN2BJsAQ/AtlH/xT8VZgn1xfswZr6cR4DhKWXqvXopAGq8is7JXYhCND3ycw1LTzHfQFJYI7dvy7p+Af9evWho4oKk9h9G5WQIkLK/c/ScgjR4M7SdA1dY4K4LW4wA7f+f3tQlfXYC3Eql1ZFV7CxFoIOUpWb8/Hxl5IbK0KFERqGYmaHDicgM+fx3SvsvLk9x01r4rN/vGL6RjaqTbk6J8avMEYjQoo6GHsaDB3hFhQR8qSMdRccLSQIMSFqv7srTZO2ZN7jX7dqqFgpb0+uT5U0effK3A51eP2kfq8drjhWr1QvkEWRQqSeZxQUdBv1I1rRhbtWTFfuPCU+Tb5eo+++/9MgW9Lb9wxkf0rppPrqbSE7bvxEzYYU4ckS/LqV0IeDK6gz/8qGmjPns2Yip0EMeGab3/jfkV1Pwg0MXUOApQFbOFLwiZXVYnHcn0OquM8fmt52e7JPdpVFbwvzUVOjZIIAxaSRSge9Bf+Kt7T1DDik/RDPvyZMg4uvh/bdSSqQdcCfgQIALY3lhdg=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
