language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: gRPs/ZS540nzDOMacQvptcLx64S1sDR9836ts75/YvTi4ps101nDGqhVlsjCYKXTe1KW4lZ/OMJ1lH3wHiqly/9aklDj7O5cHmAVPUdfId5a1Y7TMC3e3rrDNN8PLhef+BAfK211g5gPH5vuNX2uTtWzPETAgOJt/PyzDqYZoBqg8DXdFvyWbJlO04kLK6bkxQTVPbLM2XUSSv/mOwyxr28NafNDhL6YnhqE69ge3MQEHpTOtlCK81WMFQMUSZID3vbI4GlNQ/kKII+wAmM7Q999RSNmZPPP2qtObNFZ0MmW22oDDF/UwPyjQ2//OZC+H+5uywSs9tyrbI148zq3vy8gKrdSEmk3XqgXqAd120msfB/ZESLt/XL0Uom6kNpttJry8FYatXX7p24ElbmU5HvtnoYmh3pqsnEJVwpUj2QHqqYI+0ssdKSSj3a8GEXYEk4RpUe9bbyUMIAvDbYyMgRB7mCZ0aaB/VMXB/8hWuQtz1IcTDyEF5J54tB2yEcDbw4QXaAGcI0L+YPVl+Lwzty0jhBjntrDsUT1va0t5Ncl3//hCg1d0T70E413l5wgvC96KUbeAth4nDcRgrM3CFTEVTo1c1XvXEwOicQIacQFP6diZBrl/afiNT0XzPxDFCXnPjRa7O5zcdmkFIrFZbJG5jMUSGkudy9ssnKt0ec=
  - secure: pd6ty8Pe/Bo0fpZ9Txv+boDaGOs4fcGKMPAmUWU21wVX9QtwaM9LvlHodkIHE/CvACSX8wjrivAVqgo0ksZIko+x4G7zKpVUBLpEAcH2RaysYDm8Dihn9tBbTRxpBLhJvxUWcf0Wc0hiJEM3jgohXVI5d85xVtwg6uRjZzL+vGN4M1H7mtNrRsl/atqy1hyJO0565rfQeNQB/ViRJkNj0+nXzfGfk4h9j08SmKtZuF+9PH1/C1r5jntieAQYKp2V6j1ahspQTXZ1U7IHslLLEQoj71fixVPWVeGpHmAm3GgZ2DGCgaOzuMZ3jJKXxmN6fhEN7VFSOTm9ToLn6A1hkzTNfxj9gOBm0/CQvy2LB7yvzPxvLAZVMHTzKEmOYPC50nENXHHGTmxi76y0rcsUIBB1MHv2JQ8Uq3gtROCJhRtAmmzkrGlXsGVtKTVHJnE4Mts/8apksDoE6pcnhjZpk3hJhKYvRadjrpNNaNCQbrWbBN+hKb6uUAPSC44VarZqYvqcZHpLUWjK1eTR5fRTqoqjdJjI0AQOP2rgXJDN9LQO+ELNjdSQ+M6xPXklbzOUkoAnAocw1/cDDbdnc18/j2YMf3hk4qLGK7sshN08k2oCGIlcVWcpzfd2YWWT438ao9SC4S5LVAKHpwGS37LKq+P5l8qKBlpLcTg9tvC86ek=
  - secure: R6pnviTbsyeCsG92XiQpznUvqoJk4GNmJOVFsnDVuRMFc4Rq30HYdLqv4v7AY6osDG2QiUcWLRQZlQfA1PxhjM+j46hQ2wfwkL4Y+CinvCGmNU6RKoJH9BYM6gBzwmY14nfzFcn7buujFd98aH86a07yPSBiFh1EkGFsklua5dMx5zANS9o2BzS8ZixyjaFWBKyLOJclU1NKxYiBDhtFukbVqr7xDfCBqVTWejA0EXXkDDmAOB/+UmcHSZsZP1+6KWwvUBDPhMW7F7FCVG31CFR0hdn3irc65VZ0NjfhWR2qs0dTD+akcsKcy8ws7XmBia1kwwp181BXpdadZP9LUSCTN1ZDsT2uDntechHPP5vBxt2LPbMqPhXg8sCTzUmT5wqvTZ7aBql1j0BimJf1CX1hdbLN0O3g8ddIF1rM7P/ICLZOG1svSVa+QBiU0dYYMD4viMioVox8sI04kNenIPcllsIESDCInHtFh7JinsL6Gea6g5zRwtZ3rJqyQh7UT2z6TVNyrjG/1vTmYAAVXVhujE3+1ONdGWzhZFwutHk+J7cta4ITzrFyoUIlZVs3euMcx+cVlo8QCxdLcOsJNDe/saRnAokjxTbr7T6ApLuOc5JvARTHmXvb7J9hh7vhVUPvpKlacXm0E14fRWMChJH1FpEAkZyNwEMhY889dBc=
cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_99232a7c999e_key -iv $encrypted_99232a7c999e_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi